name: Godot HTML5 Export

on:
  push:
    branches:
      - main  # Trigger workflow when pushing to the main branch
  pull_request:

jobs:
  export-game:
    runs-on: ubuntu-latest  # Skift til Linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Godot
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.1.1-stable/Godot_v4.1.1-stable_linux_headless.64 -O godot
          chmod +x godot
          mv godot /usr/local/bin/godot

      - name: Ensure build directory exists
        run: mkdir -p build/html5

      - name: Export to HTML5
        run: godot --headless --verbose --export-release "HTML5" "build/html5/index.html"

      - name: Debug Build Output
        run: ls -la build/html5

      - name: Upload HTML5 Build
        uses: actions/upload-artifact@v4
        with:
          name: exported-html5
          path: build/html5/
