name: Godot HTML5 Export

on:
  push:
    branches:
      - main  # Kør workflow når vi pusher til main
  pull_request:

jobs:
  export-game:
    runs-on: windows-latest  # Skifter fra Ubuntu til Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Godot
        run: |
          Invoke-WebRequest -Uri "https://github.com/godotengine/godot/releases/download/4.1.1-stable/Godot_v4.1.1-stable_win64.exe.zip" -OutFile "godot.zip"
          Expand-Archive -Path "godot.zip" -DestinationPath "."
          Rename-Item -Path "Godot_v4.1.1-stable_win64.exe" -NewName "godot.exe"
          echo "Godot path: $(pwd)\godot.exe" >> $env:GITHUB_ENV

      - name: Ensure build directory exists
        run: mkdir build\html5

      - name: Export to HTML5
        run: |
          & "$env:GODOT_PATH" --headless --verbose --export "HTML5" "bu
