name: Godot HTML5 Export

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  export-game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and Install Godot Headless
        run: |
          GODOT_VERSION=4.1.1-stable  # <--- Opdater denne hvis der er en nyere version!
          wget https://downloads.tuxfamily.org/godotengine/$GODOT_VERSION/Godot_v$GODOT_VERSION_linux.x86_64.zip -O godot.zip
          unzip godot.zip
          chmod +x Godot_v$GODOT_VERSION_linux.x86_64
          mv Godot_v$GODOT_VERSION_linux.x86_64 /usr/local/bin/godot

      - name: Ensure build directory exists
        run: mkdir -p build/html5

      - name: Export to HTML5
        run: godot --headless --verbose --export-release "HTML5" "build/html5/index.html"

      - name: Debug Build Output
        run: ls -la build/html5

      - name: Upload HTML5 Build
        uses: actions/upload-artifact@v4
        with:
          name: exported-html5
          path: build/html5/
