name: Godot HTML5 Export

on:
  push:
    branches:
      - main  # Trigger workflow when pushing to the main branch
  pull_request:

jobs:
  export-game:
    runs-on: windows-latest  # Use a Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Godot
        run: |
          Invoke-WebRequest -Uri "https://github.com/godotengine/godot/releases/download/4.1.1-stable/Godot_v4.1.1-stable_win64.exe.zip" -OutFile "godot.zip"
          Expand-Archive -Path "godot.zip" -DestinationPath "."
          Rename-Item -Path "Godot_v4.1.1-stable_win64.exe" -NewName "godot.exe"
          echo "GODOT_PATH=$(Resolve-Path .\godot.exe)" >> $GITHUB_ENV

      - name: Ensure build directory exists
        run: mkdir build\html5 -Force

      - name: Export to HTML5
        run: |
          $godot = Resolve-Path "$env:GODOT_PATH"
          & $godot --headless --verbose --export "HTML5" "build/html5/index.html"
      
      - name: Debug Build Output
        run: |
          echo "Listing files in build/html5/"
          dir build\html5

      - name: Upload HTML5 Build
        uses: actions/upload-artifact@v4
        with:
          name: exported-html5
          path: build/html5/
